name: mzra3ti
description: A simple offline Flutter app for farmers in Morocco.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=2.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.18
  intl: ^0.20.2
  provider: ^6.0.5
  file_picker: ^8.1.4
  pdf: ^3.8.1
  printing: ^5.10.0
  share_plus: ^12.0.1
  path_provider: ^2.0.15
  url_launcher: ^6.1.12
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
